query Home {
	allProjects(first: 100, orderBy: position_ASC) {
		id
		title
		caption(markdown: false)
		url
		color {
			...ColorFragment
		}
		position
		slug
		slide {
			__typename
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
				backgroundImage {
					...ImageFragment
				}
				layout
			}
			... on ImageDoubleRecord {
				__typename
				id
				images {
					...ImageFragment
				}
				backgroundImage {
					...ImageFragment
				}
			}
			... on ImageQuadRecord {
				__typename
				id
				images {
					...ImageFragment
				}
				imageMobile {
					...ImageFragment
				}
			}
			... on VideoRecord {
				__typename
				id
				video {
					...VideoFragment
				}
				backgroundImage {
					...ImageFragment
				}
				poster {
					...ImageFragment
				}
			}
		}
	}
}
