query AllProjects {
	allProjects(first: 100, orderBy: position_ASC) {
		id
		title
		caption(markdown: false)
		captionStyle
		url
		color {
			...ColorFragment
		}
		background {
			...ColorFragment
		}
		position
		slug
		slide {
			... on VideoSlideRecord {
				__typename
				id
				video {
					...VideoFragment
				}
				poster {
					...ImageFragment
				}
				backgroundImage {
					...ImageFragment
				}
				css
			}
			... on ImageSlideRecord {
				__typename
				id
				images {
					__typename
					... on ImageRecord {
						__typename
						image {
							...ImageFragment
						}
						layout
						background {
							...ColorFragment
						}
					}
				}
				backgroundImage {
					...ImageFragment
				}
				layout
				css
			}
		}
	}
}
