fragment ImageThumbnailFragment on FileField {
	id
	mimeType
	url
	title
	alt
	height
	width
	responsiveImage(imgixParams: { q: 90, w: 300, sharp: 90 }) {
		src
		width
		height
		alt
		title
		base64
	}
}
