fragment ImageThumbnailFragment on FileField {
	id
	mimeType
	url
	title
	alt
	height
	width
	responsiveImage(imgixParams: { q: 80, ar: "1:1", w: 200, fit: clamp, auto: format }) {
		src
		width
		height
		alt
		title
		base64
	}
}
