fragment ImageFragment on ImageFileField {
	id
	mimeType
	url
	title
	alt
	height
	width
	responsiveImage(imgixParams: { w: 4000, auto: format }, sizes: "(max-width: 46.24em) 100vw") {
		src
		width
		height
		alt
		title
		base64
		sizes
	}
}
