query AllProjects($first: IntType, $skip: IntType) {
	allProjects(first: $first, skip: $skip, orderBy: position_ASC) {
		...ProjectFragment
	}
	_allProjectsMeta {
		count
	}
}

query Project($slug: String!) {
	project(filter: { slug: { eq: $slug } }) {
		...ProjectFragment
	}
}

fragment ProjectFragment on ProjectRecord {
	id
	title
	caption(markdown: false)
	captionStyle
	url
	color {
		...ColorFragment
	}
	background {
		...ColorFragment
	}
	position
	slug
	slide {
		__typename
		... on VideoSlideRecord {
			id
			video {
				...VideoFragment
			}
			poster {
				...ImageFragment
			}
			backgroundImage {
				...ImageFragment
			}
			css
		}
		... on ImageSlideRecord {
			id
			images {
				__typename
				... on ImageRecord {
					__typename
					image {
						...ImageFragment
					}
					layout
					background {
						...ColorFragment
					}
				}
			}
			backgroundImage {
				...ImageFragment
			}
			layout
			css
		}
	}
}
